#+TITLE: 1st Assignment - Intro to Parallel Computing
#+AUTHOR: Bryce Mazurowski
#+EMAIL: brycepm2@illinois.edu

NCSA Advanced Parallel Computing Cohort
Fall 2023

Due date: October 11, 2023


* 1. Describe the two pure ways of parallelism (data and task). Which one of them has the most capability to speed up computationally intensive workloads?
- Data Parallelism: When a single task is executed on a chunk of data
  that is split into pieces based on the number of threads available
  for the task
- Task Parallelism: When multiple independent tasks are executed on a single data
  source. Each task can be assigned a thread and computed
  concurrently.
- In general, data parallelism is more capable of speeding up
  computationally intensive workflows. When working with a large
  dataset, it is quicker to partition the data and work on a given
  task concurrently. Task parallelism is also more limited if one task
  depends on the operations in a different task.

* 2. What do you perceive as the best advantage of OpenMP? What is its main limitation?
The biggest advantage of OpenMP is its widespread availability. It can
be used on any operating system with basically any compiler. The fact
that it is simple to work with is a close second.

OpenMP's biggest limitation is that it is only effective on shared
memory machines. It cannot handle communication on distributed memory systems.



* 3. Write/find a simple serial program with a loop (ask ChatGPT if you can’t find one).
 1. Parallelize the loop using OpenMP directives
 2. Measure the time it takes to complete the loop with a different number of OpenMP threads (1 to 16 suggested)
 3. Repeat b) 3-6 times, take the averages, and calculate the speedup factor for each number of threads
 4. Plot your results
 5. Discuss the scalability of your parallelization. Is it far from ideal? Why?

The code takes a vector of complex numbers and computes the number of
iterations for the Mandelbrot set.
\[
f(z) = z^2 + c
\]
where $z$ and $c$ are complex numbers. $z$ is initialized to zero and
the components of $c$ are randomly generated.

Insert your serial code here
#+begin_src cpp

  #+end_src




	

Insert your parallelized code here
#+begin_src cpp

#+end_src




	

Add your plot here


Discuss the results here
