# C++ GCC compiler
CC=clang++-mp-16

# compilation flags (none)
# LDFLAGS=-fopenmp

# source file
SOURCE=./iterlinsolver.cpp

# binary name
EXEC=iterLinSolver

all:
	$(CC) $(LDFLAGS) $(SOURCE) -o $(EXEC)
	@echo -e "----- COMPILATION DONE -----"


clean:
	rm -r $(EXEC)

